=== AbelChT/RealisticCameraOpenGL/input/scene_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "scene_schema.json",
  "title": "Scene description specification",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the scene",
      "type": "string"
    },
    "textures": {
      "description": "Textures used in the scene",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the texture",
            "type": "string"
          },
          "path": {
            "description": "Path of the texture",
            "type": "string"
          }
        },
        "required": [
          "name",
          "path"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "meshes": {
      "description": "Meshes used in the scene",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the mesh",
            "type": "string"
          },
          "path": {
            "description": "Path of the mesh",
            "type": "string"
          },
          "rotate": {
            "description": "Rotate the mesh",
            "type": "boolean"
          },
          "uniform": {
            "description": "Uniform the mesh",
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "path",
          "rotate",
          "uniform"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "materials": {
      "description": "Materials used in the scene",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "Name of the material",
            "type": "string"
          },
          "color": {
            "$ref": "#/definitions/color"
          },
          "shininess": {
            "description": "Shininess factor (m)",
            "type": "number",
            "minimum": 1,
            "maximum": 300
          },
          "specular_strength": {
            "description": "Strength of specular component (C_spec)",
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "diffuse_strength": {
            "description": "Strength of diffuse component (C_diff)",
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "albedo_texture_name": {
            "description": "Texture albedo",
            "type": "string"
          },
          "normal_texture_name": {
            "description": "Texture normal",
            "type": "string"
          }
        },
        "required": [
          "name",
          "color",
          "shininess",
          "specular_strength",
          "diffuse_strength"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "objects": {
      "description": "Objects used in the scene",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "position": {
            "$ref": "#/definitions/position"
          },
          "rotation": {
            "$ref": "#/definitions/rotation"
          },
          "scale": {
            "$ref": "#/definitions/scale"
          },
          "mesh_name": {
            "description": "Name of the mesh",
            "type": "string"
          },
          "material_name": {
            "description": "Name of the material",
            "type": "string"
          }
        },
        "required": [
          "position",
          "rotation",
          "scale",
          "mesh_name",
          "material_name"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "light": {
      "description": "Light of the scene",
      "properties": {
        "position": {
          "$ref": "#/definitions/position"
        },
        "color": {
          "$ref": "#/definitions/color"
        }
      },
      "required": [
        "position",
        "color"
      ],
      "additionalProperties": false
    },
    "ambient_light": {
      "description": "Light of the scene",
      "properties": {
        "color": {
          "$ref": "#/definitions/color"
        }
      },
      "required": [
        "color"
      ],
      "additionalProperties": false
    },
    "camera": {
      "description": "Camera of the scene",
      "properties": {
        "position": {
          "$ref": "#/definitions/position"
        },
        "look_at": {
          "$ref": "#/definitions/position"
        },
        "sensor_size": {
          "description": "Size of sensor (mm)",
          "type": "number",
          "minimum": 0
        },
        "focal_length": {
          "description": "Focal length (mm)",
          "type": "number",
          "minimum": 0
        },
        "f_stop": {
          "description": "F-Stop",
          "type": "number",
          "minimum": 1
        },
        "z_far": {
          "description": "Far distance to be rendered (m)",
          "type": "number",
          "minimum": 1
        }
      },
      "required": [
        "position",
        "look_at",
        "sensor_size",
        "focal_length",
        "f_stop",
        "z_far"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "name",
    "textures",
    "meshes"
  ],
  "additionalProperties": false,
  "definitions": {
    "color": {
      "description": "Color of something",
      "type": "object",
      "properties": {
        "r": {
          "description": "Intensity of red",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "g": {
          "description": "Intensity of green, range [0, 1]",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "b": {
          "description": "Intensity of blue",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "required": [
        "r",
        "g",
        "b"
      ],
      "additionalProperties": false
    },
    "position": {
      "description": "Position",
      "type": "object",
      "properties": {
        "x": {
          "description": "Position in x (meters)",
          "type": "number"
        },
        "y": {
          "description": "Position in y (meters)",
          "type": "number"
        },
        "z": {
          "description": "Position in z (meters)",
          "type": "number"
        }
      },
      "required": [
        "x",
        "y",
        "z"
      ],
      "additionalProperties": false
    },
    "rotation": {
      "description": "Rotation",
      "type": "object",
      "properties": {
        "x": {
          "description": "Rotation in x (degrees)",
          "type": "number"
        },
        "y": {
          "description": "Rotation in y (degrees)",
          "type": "number"
        },
        "z": {
          "description": "Rotation in z (degrees)",
          "type": "number"
        }
      },
      "required": [
        "x",
        "y",
        "z"
      ],
      "additionalProperties": false
    },
    "scale": {
      "description": "Scale",
      "type": "object",
      "properties": {
        "x": {
          "description": "Scale in x",
          "type": "number",
          "minimum": 0
        },
        "y": {
          "description": "Scale in y",
          "type": "number",
          "minimum": 0
        },
        "z": {
          "description": "Scale in z",
          "type": "number",
          "minimum": 0
        }
      },
      "required": [
        "x",
        "y",
        "z"
      ],
      "additionalProperties": false
    }
  }
}

=== AbelChT/RealisticCameraOpenGL/assets/scene/scene_cans_with_plane.json
{
  "$schema": "../../input/scene_schema.json",
  "name": "Cans with plane scene",
  "textures": [
    {
      "name": "checker",
      "path": "assets/textures/checker.png"
    }
  ],
  "meshes": [
    {
      "name": "plane",
      "path": "assets/meshes/plane.obj",
      "rotate": true,
      "uniform": false
    },
    {
      "name": "can",
      "path": "assets/meshes/can.obj",
      "rotate": true,
      "uniform": false
    }
  ],
  "materials": [
    {
      "name": "mate_blue",
      "color": {
        "r": 0.12,
        "g": 0.12,
        "b": 1.0
      },
      "shininess": 32.0,
      "specular_strength": 0.5,
      "diffuse_strength": 1.0
    },
    {
      "name": "mate_red",
      "color": {
        "r": 1.0,
        "g": 0.12,
        "b": 0.12
      },
      "shininess": 32.0,
      "specular_strength": 0.5,
      "diffuse_strength": 1.0
    },
    {
      "name": "mate_green",
      "color": {
        "r": 0.12,
        "g": 1.0,
        "b": 0.12
      },
      "shininess": 32.0,
      "specular_strength": 0.5,
      "diffuse_strength": 1.0
    },
    {
      "name": "mate_green_red",
      "color": {
        "r": 0.7,
        "g": 0.7,
        "b": 0.12
      },
      "shininess": 32.0,
      "specular_strength": 0.5,
      "diffuse_strength": 1.0
    },
    {
      "name": "checker",
      "color": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "shininess": 32.0,
      "specular_strength": 0.5,
      "diffuse_strength": 1.0,
      "albedo_texture_name": "checker"
    }
  ],
  "objects": [
    {
      "position": {
        "x": 0,
        "y": -0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_green"
    },
    {
      "position": {
        "x": 0,
        "y": 0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_green"
    },
    {
      "position": {
        "x": -0.2,
        "y": 0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_red"
    },
    {
      "position": {
        "x": -0.2,
        "y": -0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_red"
    },
    {
      "position": {
        "x": -0.4,
        "y": 0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_blue"
    },
    {
      "position": {
        "x": -0.4,
        "y": -0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_blue"
    },
    {
      "position": {
        "x": -0.6,
        "y": 0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_green"
    },
    {
      "position": {
        "x": -0.6,
        "y": -0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_green"
    },
    {
      "position": {
        "x": -0.8,
        "y": 0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_red"
    },
    {
      "position": {
        "x": -0.8,
        "y": -0.1,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "can",
      "material_name": "mate_red"
    },
    {
      "position": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 1,
        "y": 1,
        "z": 1
      },
      "mesh_name": "plane",
      "material_name": "checker"
    }
  ],
  "light": {
    "position": {
      "x": 3,
      "y": 0,
      "z": 4.5
    },
    "color": {
      "r": 0.5,
      "g": 0.5,
      "b": 0.5
    }
  },
  "ambient_light": {
    "color": {
      "r": 0.1,
      "g": 0.1,
      "b": 0.1
    }
  },
  "camera": {
    "position": {
      "x": 1.0,
      "y": 0,
      "z": 0.4
    },
    "look_at": {
      "x": 0.0151922703,
      "y": 0,
      "z": 0.226351783
    },
    "sensor_size": 30.0,
    "focal_length": 32.0,
    "f_stop": 1.0,
    "z_far": 1000
  }
}
